# -- Main Menu --

[[main]]
  name = "Posts"
  pageRef = "post"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

[[main]]
  name = "Tags"
  pageRef = "tags"
  weight = 30

[[main]]
  name = "Archives"
  pageRef = "archives"
  weight = 40

[[main]]
  name = "About"
  url = "/about/me/"
  weight = 50

# -- Footer Menu --

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 20
