# -- Theme Parameters --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

disableImageOptimization = false
disableTextInHeader = false
hotlinkFeatureImage = true

highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

# SEO
defaultSocialImage = "img/cover.jpg"
enableStructuredBreadcrumbs = true

[header]
  layout = "basic"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  homepageImage = "img/cover.jpg"
  showRecent = true
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "/post/"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showDateUpdated = true
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = true
  showZenMode = false

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  groupByYear = true
  cardView = true
  cardViewScreenWidth = false

[sitemap]
  excludedKinds = ["taxonomy", "term"]

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = false
  showTableOfContents = false
  cardView = true

[term]
  showHero = false
  showBreadcrumbs = false
  showTableOfContents = true
  groupByYear = false
  cardView = true
  cardViewScreenWidth = false
